module.exports = {
  host: 'surgery.ru:80',
  logo: 'fleboteka',
  color_main: '#224592',
  color_main_light: '#73B3FF',
  color_main_ultra_light: '#EEF4F6',
  color_red: '#FF6E74',
  color_grey: '#979797',
  color_second: '#E9EEEF',
  color_link: '#224592',
  color_link_hover: '#2C66DE',
  button_bg_hover: '#3260C1',
  button_bg_active: '#169E6B',
  button_bg_disabled: '#D8E4E6',
  color_main_background: '#34293F',
  menu_class: 'menu_fleboteka',
  name: 'Флеботека',
  name_eng: 'Fleboteka',
};
