module.exports = {
  API_HOST: 'https://cardioteka.ru/api',
  host: 'cardioteka.ru',
  logo: 'cardioteka',
  color_main: '#1CA974',
  color_main_light: '#9ECBC3',
  color_main_ultra_light: '#EEF4F6',
  color_red: '#FF6E74',
  color_grey: '#979797',
  color_second: '#E9EEEF',
  color_link: '#1CA974',
  color_link_hover: '#1CA974',
  button_bg_hover: '#14BF7E',
  button_bg_active: '#169E6B',
  button_bg_disabled: '#D8E4E6',
  color_main_background: '#273646',
  menu_class: 'menu_default',
  name: 'Кардиотека',
  name_eng: 'Cardioteka',
  slogan: 'Для врачей, которые работают с сердцем',
  name_tagline: 'портал для кардиологов и терапевтов',
  description: 'Портал для кардиологов и терапевтов.<br/>Статьи, видеолекции, мероприятия, общение с коллегами и взаимопомощь.',
};
