export const URL_API = `${API_URL}`;

export const URL_API_FAVORITES = `${URL_API}/activity/favorites/`;
export const FAVORITES_START = 'FAVORITES_START';
export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
export const FAVORITES_FAILURE = 'FAVORITES_FAILURE';
export const FAVORITES_PATCH_SUCCESS = 'FAVORITES_PATCH_SUCCESS';
export const FAVORITES_PATCH_FAILURE = 'FAVORITES_FAILURE';
export const FAVORITES_CANCEL = 'FAVORITES_CANCEL';

export const FAVORITES_SUMMARY_SUCCESS = 'FAVORITES_SUMMARY_SUCCESS';
export const FAVORITES_SUMMARY_FAILURE = 'FAVORITES_SUMMARY_FAILURE';

export const URL_API_REMINDERS = `${URL_API}/activity/reminders/`;
export const REMINDERS_SUCCESS = 'REMINDERS_SUCCESS';
export const REMINDERS_START = 'REMINDERS_START';
export const REMINDERS_ERROR = 'REMINDERS_ERROR';
export const REMINDERS_PATCH_SUCCESS = 'REMINDERS_SUCCESS';
export const REMINDERS_PATCH_FAILURE = 'REMINDERS_FAILURE';
export const REMINDERS_CANCEL = 'REMINDERS_CANCEL';

export const URL_API_VOTES = `${URL_API}/activity/votes/`;
export const VOTES_PATCH_SUCCESS = 'VOTES_PATCH_SUCCESS';
export const VOTES_PATCH_ERROR = 'VOTES_PATCH_ERROR';

export const RESET_ACTIVITY_PAGE = 'RESET_ACTIVITY_PAGE';

export const URL_API_COMMENTS_OWN = `${URL_API}/activity/comments/`;
export const COMMENTS_OWN_START = 'COMMENTS_OWN_START';
export const COMMENTS_OWN_SUCCESS = 'COMMENTS_OWN_SUCCESS';
export const COMMENTS_OWN_FAILURE = 'COMMENTS_OWN_FAILURE';
