export const URL_API = `${API_URL}`;

export const URL_API_ARTICLES = `${URL_API}/articles/`;
export const URL_API_ARTICLE_REQUESTS = `${URL_API}/articles/requests/`;
export const URL_API_ARTICLE_QUIZ_COMPLETE = `${URL_API}/quiz/complete/`;// Нужно заменить по готовности Жени

export const ARTICLES_LIST_SUCCESS = 'ARTICLES_LIST_SUCCESS';
export const ARTICLES_SUMMARY_SUCCESS = 'ARTICLES_SUMMARY_SUCCESS';
export const ARTICLES_LIST_ERROR = 'ARTICLES_LIST_ERROR';
export const ARTICLES_SUMMARY_ERROR = 'ARTICLES_SUMMARY_ERROR';
export const ARTICLES_LIST_START = 'ARTICLES_LIST_START';
export const ARTICLES_LIST_CANCEL = 'ARTICLES_LIST_CANCEL';
export const ARTICLES_FILTER = 'ARTICLES_FILTER';

export const URL_DISEASES_IDS = `${URL_API}/articles/diseases/`;
export const URL_API_TREATMENTS_IDS = `${URL_API}/articles/treatments/`;
export const DISEASES_IDS_SUCCES = 'DISEASES_IDS_SUCCES';
export const DISEASES_IDS_FAILURE = 'DISEASES_IDS_FAILURE';
export const TREATMENTS_IDS_SUCCES = 'TREATMENTS_IDS_SUCCES';
export const TREATMENTS_IDS_FAILURE = 'TREATMENTS_IDS_FAILURE';
export const DISEASES_IDS_CANCEL = 'DISEASES_IDS_CANCEL';
export const TREATMENTS_IDS_CANCEL = 'TREATMENTS_IDS_CANCEL';

export const ARTICLE_QUIZ_SEND_START = 'ARTICLE_QUIZ_SEND_START';
export const ARTICLE_QUIZ_SEND_SUCCESS = 'ARTICLE_QUIZ_SEND_SUCCESS';
export const ARTICLE_QUIZ_SEND_ERROR = 'ARTICLE_QUIZ_SEND_ERROR';
export const ARTICLE_QUIZ_SEND_CANCEL = 'ARTICLE_QUIZ_SEND_CANCEL';

export const ARTICLE_CURRENT_START = 'ARTICLE_CURRENT_START';
export const ARTICLE_CURRENT_SUCCESS = 'ARTICLE_CURRENT_SUCCESS';
export const ARTICLE_CURRENT_ERROR = 'ARTICLE_CURRENT_ERROR';
export const ARTICLE_CURRENT_CANCEL = 'ARTICLE_CURRENT_CANCEL';

export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE';

export const ARTICLE_POPULAR_START = 'ARTICLE_POPULAR_START';
export const URL_API_ARTICLE_POPULAR = `${URL_API}/activity/popular-subjects/`;
export const ARTICLE_POPULAR_SUCCESS = 'ARTICLE_POPULAR_SUCCESS';
export const ARTICLE_POPULAR_ERROR = 'ARTICLE_POPULAR_ERROR';
export const ARTICLE_POPULAR_CANCEL = 'ARTICLE_POPULAR_CANCEL';

export const ARTICLES_CANCEL = 'ARTICLES_CANCEL';

export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START';
export const API_CREATE_ARTICLE = `${URL_API}/articles/requests/`;
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';
export const CREATE_ARTICLE_CANCEL = 'CREATE_ARTICLE_CANCEL';

export const EDIT_ARTICLE_START = 'EDIT_ARTICLE_START';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_ERROR = 'EDIT_ARTICLE_ERROR';
export const EDIT_ARTICLE_CANCEL = 'EDIT_ARTICLE_CANCEL';

export const EDIT_ARTICLE_SUBMIT_START = 'EDIT_ARTICLE_SUBMIT_START';
export const EDIT_ARTICLE_SUBMIT_SUCCESS = 'EDIT_ARTICLE_SUBMIT_SUCCESS';
export const EDIT_ARTICLE_SUBMIT_ERROR = 'EDIT_ARTICLE_SUBMIT_ERROR';
export const EDIT_ARTICLE_SUBMIT_CANCEL = 'EDIT_ARTICLE_SUBMIT_CANCEL';

export const REMOVE_REQUEST_ERROR = 'REMOVE_REQUEST_ERROR';
