export const URL_API = `${API_URL}`;

export const URL_API_CONSILIUM = `${URL_API}/concilium/problems`;

export const CONSILIUM_START = 'CONSILIUM_START';
export const CONSILIUM_SUCCESS = 'CONSILIUM_SUCCESS';
export const CONSILIUM_FAILURE = 'CONSILIUM_FAILURE';
export const CONSILIUM_POST_SUCCESS = 'CONSILIUM_POST_SUCCESS';
export const CONSILIUM_POST_FAILURE = 'CONSILIUM_POST_FAILURE';
export const CONSILIUM_CANCEL = 'CONSILIUM_CANCEL';
export const CONSILIUM_NOTIFICATION_CANCEL = 'COMMENT_NOTIFICATION_CANCEL';

export const CURRENT_CONSILIUM_SUCCESS = 'CURRENT_CONSILIUM_SUCCESS';

export const CONSILIUM_QUESTION_SUCCESS = 'CONSILIUM_QUESTION_SUCCESS';
export const CONSILIUM_QUESTION_FAILURE = 'CONSILIUM_QUESTION_FAILURE';

export const EDIT_CONSILIUM_SUCCESS = 'EDIT_CONSILIUM_SUCCESS';
export const EDIT_CONSILIUM_FAILURE = 'EDIT_CONSILIUM_FAILURE';

export const CONSILIUM_FILTER = 'CONSILIUM_FILTER';

export const CONSILIUM_HARD_RESET = 'CONSILIUM_HARD_RESET';
