export const URL_API = `${API_URL}`;

export const URL_API_NEWS = `${URL_API}/news/`;

export const NEWS_START = 'NEWS_START';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAILURE = 'NEWS_FAILURE';
export const NEWS_POST_SUCCESS = 'NEWS_POST_SUCCESS';
export const NEWS_POST_FAILURE = 'NEWS_POST_FAILURE';
export const NEWS_CANCEL = 'NEWS_CANCEL';
export const NEWS_NOTIFICATION_CANCEL = 'COMMENT_NOTIFICATION_CANCEL';

export const CURRENT_NEWS_SUCCESS = 'CURRENT_NEWS_SUCCESS';

export const NEWS_QUESTION_SUCCESS = 'NEWS_QUESTION_SUCCESS';
export const NEWS_QUESTION_FAILURE = 'NEWS_QUESTION_FAILURE';

export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS';
export const EDIT_NEWS_FAILURE = 'EDIT_NEWS_FAILURE';

export const NEWS_FILTER = 'NEWS_FILTER';

export const NEWS_HARD_RESET = 'NEWS_HARD_RESET';
