export const URL_API = `${API_URL}`;
export const URL_API_PROFILE = `${API_URL}/users/profile/`;
export const URL_API_PROFILE_PHOTO = `${API_URL}/users/profile/avatar/`;
export const URL_PROFILE_RESET_PASSWORD = `${API_URL}/users/password/reset/complete/`;

export const PROFILE_USER_UPDATE = 'PROFILE_USER_UPDATE';
export const PROFILE_USER_ERROR = 'PROFILE_USER_ERROR';

export const PROFILE_RESET_PASSWORD_START = 'PROFILE_RESET_PASSWORD_START';
export const PROFILE_RESET_PASSWORD_SUCCESS = 'PROFILE_RESET_PASSWORD_SUCCESS';
export const PROFILE_RESET_PASSWORD_ERROR = 'PROFILE_RESET_PASSWORD_ERROR';
export const PROFILE_RESET_PASSWORD_CANCEL = 'PROFILE_RESET_PASSWORD_CANCEL';

export const PROFILE_RESET_ALL = 'PROFILE_RESET_ALL';

export const URL_API_GET_SUMMARY = `${API_URL}/activity/summary/count`;
export const GET_SUMMARY_LOADING = 'GET_SUMMARY_LOADING';
export const GET_SUMMARY_FAIL = 'GET_SUMMARY_FAIL';
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS';
