export const URL_API = `${API_URL}`;

export const URL_API_VIDEOTEKA = `${URL_API}/video-library/videos/`;
export const URL_API_CURRENT_VIDEOTEKA = `${URL_API}/video-library/videos/`;

export const VIDEOTEKA_FILTER = 'VIDEOTEKA_FILTER';
export const VIDEOTEKA_START = 'VIDEOTEKA_START';
export const VIDEOTEKA_SUCCESS = 'VIDEOTEKA_SUCCESS';
export const CURRENT_VIDEOTEKA_SUCCESS = 'CURRENT_VIDEOTEKA_SUCCESS';
export const VIDEOTEKA_FAILURE = 'VIDEOTEKA_FAILURE';
export const VIDEOTEKA_CANCEL = 'VIDEOTEKA_CANCEL';

export const URL_API_COURSES = `${URL_API}/video-library/courses/`;
export const COURSES_SUCCESS = 'COURSES_SUCCESS';
export const COURSES_FAILURE = 'COURSES_FAILURE';

export const URL_API_THEMES = `${URL_API}/video-library/themes/`;
export const THEMES_SUCCESS = 'THEMES_SUCCESS';
export const THEMES_FAILURE = 'THEMES_FAILURE';

export const TOGGLE_VIDEOTEKA_SUCCESS = 'TOGGLE_VIDEOTEKA_SUCCESS';

export const VIDEOTEKA_SUMMARY_ERROR = 'VIDEOTEKA_SUMMARY_ERROR';
export const VIDEOTEKA_SUMMARY_SUCCESS = 'VIDEOTEKA_SUMMARY_SUCCESS';
